---
# the arguments in here will be varied
activation_kwargs:
    w0: [10., 10., 15., 15., 20., 20., 25., 25., 30., 30., 35., 35.]

learning_rate: [1.5e-4, 3.e-4, 1.5e-4, 3.e-4, 1.5e-4, 3.e-4, 1.5e-4, 3.e-4, 1.5e-4, 3.e-4, 1.5e-4, 3.e-4]

---
# shared configuration
architecture: ./model_components
model_type: inr_modules.CombinedINR  # Changed to CombinedINR for audio
model_config:
  in_size: 1  # Changed to 1 for time dimension input
  out_size: 1  # Changed to 1 for audio amplitude output
  terms:
    - [inr_modules.MLPINR.from_config, {
        hidden_size: 256,
        num_layers: 5,
        layer_type: inr_layers.SirenLayer,
        num_splits: 1,
        use_complex: false,
        initialization_scheme: initialization_schemes.siren_scheme,
        positional_encoding_layer: [inr_layers.ClassicalPositionalEncoding.from_config, {
          num_frequencies: 10
        }]
      }]

trainer_module: ./inr_utils/
trainer_type: training.train_inr_scan

loss_evaluator: losses.SoundLossEvaluator
loss_function: losses.SoundLossEvaluator
loss_evaluator_config:
  time_domain_weight: 1.0
  frequency_domain_weight: 0.0001



sampler: [sampling.SoundSampler, {
    window_size: 256,
    batch_size: 64,
    allow_pickle: true,
    fragment_length: null,  # Will be set when loading
    sound_fragment: ./example_data/data_gt_bach.npy  # Use NPY file directly
}]

optimizer: adam
optimizer_config:
  b1: 0.8
  b2: 0.999999
steps: 20000

---
# post-processing configuration
components_module: ./inr_utils/
post_processor_type: post_processing.PostProcessor
metrics: 
  - [metrics.AudioMetricsOnGrid, {
      target_audio: ./example_data/data_gt_bach.npy,
      grid_size: 2040,
      batch_size: 1024,
      sr: 16000,
      frequency: every_n_batches
    }]

storage_directory: results/audio_experiment
wandb_kwargs:
  project: inr_edu_24
  group: audio_experiment

# Callback configuration
after_step_callback: callbacks.ComposedCallback
after_step_callback_config:
  callbacks:
    - [callbacks.print_loss, {after_every: 10}]
    - callbacks.report_loss
    - callbacks.raise_error_on_nan
    - [callbacks.AudioMetricsWithEarlyStoppingCallback, {
        metric_collector: [metrics.MetricCollector, {
          metrics: [[metrics.AudioMetricsOnGrid, {
            target_audio: ./example_data/data_gt_bach.wav,
            grid_size: 2040,
            batch_size: 1024,
            sr: 16000,
            frequency: every_n_batches
          }]],
          batch_frequency: 100,
          epoch_frequency: 1
        }],
        print_metrics: true,
        print_frequency: 100,
        patience: 100,
        min_delta: 0.001,
        monitor: audio_mse
      }]
  use_wandb: true
  show_logs: false