---
# the arguments in here will be varried
data_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
---
# the arguments in here will be shared across experiments :)
architecture: ./model_components
model_type: inr_modules.MLPINR.from_config
model_config:
  in_size: 2
  out_size: 3
  hidden_size: 256
  num_layers: 5
  layer_type: inr_layers.SirenLayer
  activation_kwargs: {w0: 15}
  num_splits: 1

trainer_module: ./inr_utils/
trainer_type: training.train_inr_scan

loss_evaluator: losses.PointWiseLossEvaluator
target_function: images.ContinuousImage
target_function_config:
  image: 
    - DIV2K/DIV2K_entropy_5p_25p/0012.png
    - DIV2K/DIV2K_entropy_5p_25p/0024.png
    - DIV2K/DIV2K_entropy_5p_25p/0033.png
    - DIV2K/DIV2K_entropy_5p_25p/0034.png
    - DIV2K/DIV2K_entropy_5p_25p/0037.png
    - DIV2K/DIV2K_entropy_5p_25p/0042.png
    - DIV2K/DIV2K_entropy_5p_25p/0058.png
    - DIV2K/DIV2K_entropy_5p_25p/0081.png
    - DIV2K/DIV2K_entropy_5p_25p/0096.png
    - DIV2K/DIV2K_entropy_5p_25p/0144.png
    - DIV2K/DIV2K_entropy_5p_25p/0168.png
    - DIV2K/DIV2K_entropy_5p_25p/0183.png
    - DIV2K/DIV2K_entropy_5p_25p/0195.png
    - DIV2K/DIV2K_entropy_5p_25p/0196.png
    - DIV2K/DIV2K_entropy_5p_25p/0202.png
    - DIV2K/DIV2K_entropy_5p_25p/0203.png
    - DIV2K/DIV2K_entropy_5p_25p/0211.png
    - DIV2K/DIV2K_entropy_5p_25p/0213.png
    - DIV2K/DIV2K_entropy_5p_25p/0214.png
    - DIV2K/DIV2K_entropy_5p_25p/0218.png
    - DIV2K/DIV2K_entropy_5p_25p/0221.png
    - DIV2K/DIV2K_entropy_5p_25p/0258.png
    - DIV2K/DIV2K_entropy_5p_25p/0225.png
    - DIV2K/DIV2K_entropy_5p_25p/0248.png
    - DIV2K/DIV2K_entropy_5p_25p/0268.png
    - DIV2K/DIV2K_entropy_5p_25p/0252.png
  scale_to_01: true
  interpolation_method: images.make_piece_wise_constant_interpolation
loss_function: losses.scaled_mse_loss

sampler: sampling.GridSubsetSampler
sampler_config:
  size: [2040, 1356]
  batch_size: 2000
  allow_duplicates: true

optimizer: adam
learning_rate: 1.5e-4
steps: 40000

---
# this determines how the results will be processed after training
# because we can't log to wandb when we're training multiple networks in parallel using vmap, this all happens after training
components_module: ./inr_utils/
post_processor_type: post_processing.PostProcessor
metrics: 
  - [metrics.MSEOnFixedGrid, {grid: [2040, 1356], batch_size: 8160, frequency: every_n_batches}]
  - [metrics.PlotOnGrid2D, {grid: 256, batch_size: 2048, frequency: every_n_batches, use_wandb: true}]
storage_directory: results/example_experiment
wandb_kwargs:
  project: inr_edu_24
  group: example2  # set a group parameter to filter later on in wandb

# for some of the metrics
target_function: images.ContinuousImage
target_function_config:
  image: 
    - DIV2K/DIV2K_entropy_5p_25p/0012.png
    - DIV2K/DIV2K_entropy_5p_25p/0024.png
    - DIV2K/DIV2K_entropy_5p_25p/0033.png
    - DIV2K/DIV2K_entropy_5p_25p/0034.png
    - DIV2K/DIV2K_entropy_5p_25p/0037.png
    - DIV2K/DIV2K_entropy_5p_25p/0042.png
    - DIV2K/DIV2K_entropy_5p_25p/0058.png
    - DIV2K/DIV2K_entropy_5p_25p/0081.png
    - DIV2K/DIV2K_entropy_5p_25p/0096.png
    - DIV2K/DIV2K_entropy_5p_25p/0144.png
    - DIV2K/DIV2K_entropy_5p_25p/0168.png
    - DIV2K/DIV2K_entropy_5p_25p/0183.png
    - DIV2K/DIV2K_entropy_5p_25p/0195.png
    - DIV2K/DIV2K_entropy_5p_25p/0196.png
    - DIV2K/DIV2K_entropy_5p_25p/0202.png
    - DIV2K/DIV2K_entropy_5p_25p/0203.png
    - DIV2K/DIV2K_entropy_5p_25p/0211.png
    - DIV2K/DIV2K_entropy_5p_25p/0213.png
    - DIV2K/DIV2K_entropy_5p_25p/0214.png
    - DIV2K/DIV2K_entropy_5p_25p/0218.png
    - DIV2K/DIV2K_entropy_5p_25p/0221.png
    - DIV2K/DIV2K_entropy_5p_25p/0258.png
    - DIV2K/DIV2K_entropy_5p_25p/0225.png
    - DIV2K/DIV2K_entropy_5p_25p/0248.png
    - DIV2K/DIV2K_entropy_5p_25p/0268.png
    - DIV2K/DIV2K_entropy_5p_25p/0252.png
  scale_to_01: true
  interpolation_method: images.make_piece_wise_constant_interpolation
  data_index: None

